notifications:
  email:
    on_success: never
    on_failure: change

### workaround needed to be able to run conventional-changelog-lint on travis
before_install:
# Create a master branch for conventional-changelog-lint
- git remote set-branches origin master
- git fetch
- git checkout master
# Check out the commit that TravisCI started on:
- git checkout -

install:
- npm install -g web-ext
- npm install -g flow-bin

script:
- 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
- flow check
- npm run changelog-lint

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

language: node_js
node_js:
  - "4"

env:
  global:
    - APM_TEST_PACKAGES="linter"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
  - master

### cache node_modules/ dir between builds on travis
cache:
  directories:
    - node_modules
